# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pb/svc/unit/chat/chat.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'pb/svc/unit/chat/chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pb.svc.unit.common import msg_pb2 as pb_dot_svc_dot_unit_dot_common_dot_msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bpb/svc/unit/chat/chat.proto\x12\x04\x63hat\x1a\x1cpb/svc/unit/common/msg.proto\".\n\x0b\x43hatRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\"=\n\x0c\x43hatResponse\x12\r\n\x05reply\x18\x01 \x01(\t\x12\x1e\n\x06status\x18\x02 \x01(\x0b\x32\x0e.common.Status2G\n\x0b\x43hatService\x12\x38\n\rStreamMessage\x12\x11.chat.ChatRequest\x1a\x12.chat.ChatResponse0\x01\x42(\n\x19\x63om.plantify.pb.unit.chatB\tChatProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb.svc.unit.chat.chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.plantify.pb.unit.chatB\tChatProtoP\001'
  _globals['_CHATREQUEST']._serialized_start=67
  _globals['_CHATREQUEST']._serialized_end=113
  _globals['_CHATRESPONSE']._serialized_start=115
  _globals['_CHATRESPONSE']._serialized_end=176
  _globals['_CHATSERVICE']._serialized_start=178
  _globals['_CHATSERVICE']._serialized_end=249
# @@protoc_insertion_point(module_scope)
